package com.apps.mounir.funwithflags.Resources;

import com.apps.mounir.funwithflags.R;

/**
 * Created by mounir on 07.02.2016.
 */
public class ASIA {


    public static int[] Asia =
            {
                    R.drawable._afghanistan,
                    R.drawable._armenia,
                    R.drawable._azerbaijan,
                    R.drawable._bahrain,
                    R.drawable._bangladesh,
                    R.drawable._bhutan,
                    R.drawable._brunei,
                    R.drawable._cambodia,
                    R.drawable._china,
                    R.drawable._cyprus,
                    R.drawable._georgia,
                    R.drawable._india,
                    R.drawable._indonesia,
                    R.drawable._iran,
                    R.drawable._iraq,
                    R.drawable._israel,
                    R.drawable._japan,
                    R.drawable._jordan,
                    R.drawable._kazakhstan,
                    R.drawable._korea_north,
                    R.drawable._korea_south,
                    R.drawable._kuwait,
                    R.drawable._kyrgyzstan,
                    R.drawable._laos,
                    R.drawable._lebanon,
                    R.drawable._malaysia,
                    R.drawable._maldives,
                    R.drawable._mongolia,
                    R.drawable._myanmar,
                    R.drawable._nepal,
                    R.drawable._oman,
                    R.drawable._pakistan,
                    R.drawable._palestinian,
                    R.drawable._philippines,
                    R.drawable._qatar,
                    R.drawable._russia,
                    R.drawable._saudi_arabia,
                    R.drawable._singapore,
                    R.drawable._sri_lanka,
                    R.drawable._syria,
                    R.drawable._tajikistan,
                    R.drawable._thailand,
                    R.drawable._east_timor,
                    R.drawable._turkey,
                    R.drawable._turkmenistan,
                    R.drawable._united_arab_emirates,
                    R.drawable._uzbekistan,
                    R.drawable._vietnam,
                    R.drawable._yemen
            };

    public static String Areas[] = {
            " 652, 230",
            "29, 743",
            "86,600 ",
            "760 ",
            "143,998",
            "38,394",
            "5,765 ",
            "181,035",
            "9,596,961 ",
            "9,251 ",
            "69,700 ",
            "3,287,263 ",
            "1,904,569",
            "1,648,195 ",
            " 438,317",
            "20,770",
            "377,915",
            "89,342 ",
            "2,724,900 ",
            "120,538 ",
            "99,720 ",
            " 17,818 ",
            "199,951 ",
            "236,800 ",
            "10,400",
            "329,847 ",
            "298 ",
            "1,564,116",
            "676,578",
            "147,181 ",
            "309,500",
            "796,095 ",
            "5,655",
            "300,000 ",
            "11,586",
            "17,098,242 ",
            "2,149,690 ",
            "697 ",
            "65,610 ",
            "185,180 ",
            "143,100",
            "513,120",
            "14,874 ",
            "783,562 ",
            "488,100 ",
            "83,600",
            "447,400 ",
            "332,698 ",
            "527,968 "
    };

    public static String CApitals[] = {
            "Kabul\n" + " : کابل ",
            "erevan\n" + "         Երևան ",
            "Baku\n" + " Bakı",
            " Manama\n" + " المنامة ",
            " Dhaka\n" + "  ঢাকা ",
            "Thimphu\n" + "  ཐིམ་ཕུ",
            " Bandar Seri \nBegawan",
            "Phnom Penh\n" + "ភ្នំពេញ ",
            "Beijing\n" + "北京 ",
            " Nicosia\n" + "        Λευκωσία \n" + "        Lefkoşa",
            "Tbilisi \n" + "        თბილისი ",
            "New Delhi\n" + "  : नई दिल्ली ",
            "Jakarta",
            " Tehran\n" + "         تهران",
            "Baghdad\n" + "        : بغداد",
            "Jerusalem \n" + " ירושלים",
            "Tokyo\n" + "    東京都",
            "Amman\n" + "    عمان ",
            " Astana\n" + "    Астана",
            "Pyongyang\n" + "   평양 ",
            "Seoul\n" + "      서울 ",
            "Kuwait City\n" + " الكويت",
            "Bishkek\n" + "        Бишкек",
            " Vientiane\n" + "Lao: ວຽງຈັນ ",
            "Beirut\n" + "        بيروت ",
            "Kuala Lumpur",
            " Malé / Male'\n" + "    މާލެ ",
            " Ulaanbaatar\n" + "   Улаанбаатар",
            "Nay Pyi Taw\n" + "     နေပြည်တော်",
            "Kathmandu\n" + "      काठमाडौं",
            "Muscat\n" + "    مسقط ",
            "Islamabad",
            "El Quds",
            "Manila",
            " Doha\n" + ": الدوحة",
            "Moscow\n" + ": Москва ",
            "Riyadh\n" + ": الرياض",
            "Singapore\n" + ": 新加坡\n : சிங்கப்பூர்",
            "Sri Jayawardenapura\n Kotte",
            " Damascus\n" + ": دمشق ",
            "Dushanbe\n" + ": Душанбе",
            " Bangkok\n" + ": กรุงเทพ",
            "Dili",
            " Ankara",
            " Ashgabat\n" + ": Aşgabat",
            "Abu Dhabi\n" + ": أبوظبي ",
            "Tashkent",
            " Hanoi\n" + ": Hà Nội",
            "Sana'a\n" + ": صنعاء "
    };
    public static int phonecodes[] = {
            93,
            374,
            994,
            973,
            880,
            9751,
            673,
            855,
            86,
            357,
            995,
            91,
            62,
            98,
            964,
            972,
            81,
            962,
            7,
            850,
            82,
            965,
            996,
            856,
            961,
            60,
            960,
            976,
            95,
            977,
            968,
            92,
            970,
            63,
            974,
            7,
            966,
            65,
            94,
            963,
            992,
            66,
            670,
            90,
            993,
            971,
            998,
            84,
            967
    };
    public static String Names[] = {
            " Islamic Republic of Afghanistan",
            "Republic of Armenia",
            "Republic of Azerbaijan",
            "Kingdom of Bahrain",
            "People's Republic of Bangladesh",
            "Kingdom of Bhutan",
            "Brunei Darussalam",
            "Kingdom of Cambodia",
            "People's Republic of China",
            "Republic of Cyprus",
            "Georgia",
            "Republic of India",
            "Republic of Indonesia",
            "Islamic Republic of Iran",
            "Republic of Iraq",
            "State of Israel",
            "Japan",
            "Hashemite Kingdom of Jordan",
            "Republic of Kazakhstan",
            "Democratic People's Republic of Korea",
            "Republic of South Korea",
            "State of Kuwait",
            "Kyrgyz Republic",
            "Lao People's Democratic Republic",
            "Lebanese Republic",
            "Malaysia",
            "Republic of Maldives",
            "Mongolia",
            "Republic of the Union of Myanmar",
            "Federal Democratic Republic of Nepal",
            "Sultanate of Oman",
            "Islamic Republic of Pakistan",
            "Free State of Palestine",
            "Republic of the Philippines",
            "State of Qatar",
            "Russian Federation",
            "Kingdom of Saudi Arabia",
            "Republic of Singapore",
            "Democratic Socialist Republic of Sri Lanka",
            "Syrian Arab Republic",
            "Republic of Tajikistan",
            "Kingdom of Thailand",
            "Democratic Republic of Timor-Leste",
            "Republic of Turkey",
            "Turkmenistan",
            "United Arab Emirates",
            "Uzbekistan",
            "Republic of Uzbekistan",
            "Socialist Republic of Vietnam",
            "Yemen"
    };

    public static String Currencies[] = {
            "Afghan afghani",
            "Armenian dram",
            "Azerbaijani manat",
            "Bahraini dinar",
            "Taka",
            "Bhutanese ngultrum",
            " Brunei dollar",
            "Cambodian riel",
            "Renminbi (yuan)",
            "Euro",
            "Lari",
            "Indian Rupee",
            "Rupiah",
            "Iranian rial",
            "Iraqi dinar",
            "Israeli new shekel",
            "Yen",
            "Jordanian dinar",
            "Kazakhstani tenge",
            "North Korean won",
            "South Korean won",
            "Kuwaiti dinar",
            "Kyrgyzstani som",
            "Lao kip",
            "Lebanese pound",
            "Ringgit",
            "Maldivian rufiyaa",
            "Mongolian tögrög",
            "Kyat",
            "Nepalese rupee",
            "Omani rial",
            "Pakistani Rupee",
            "Jordan Dinar",
            "Philippine Peso",
            "Qatari riyal",
            "Russian Ruble",
            "Saudi riyal",
            "Singapore dollar",
            "Sri Lankan rupee",
            "Syrian pound",
            "Somoni",
            "Baht",
            "US Dollar",
            "Turkish lira",
            "Turkmen new manat",
            "UAE dirham",
            "Uzbekistan som",
            "đồng",
            "Yemeni rial",
    };
}
