package com.apps.mounir.funwithflags.Resources;

import com.apps.mounir.funwithflags.R;

/**
 * Created by mounir on 07.02.2016.
 */
public class EUROPE {


    public static int[] Europe =
            {
                    R.drawable._albania,
                    R.drawable._andorra,
                    R.drawable._armenia,
                    R.drawable._austria,
                    R.drawable._azerbaijan,
                    R.drawable._belarus,
                    R.drawable._belgium,
                    R.drawable._bosnia_and_herzegovina,
                    R.drawable._bulgaria,
                    R.drawable._croatia,
                    R.drawable._cyprus,
                    R.drawable._czech_republic,
                    R.drawable._denmark,
                    R.drawable._estonia,
                    R.drawable._finland,
                    R.drawable._france,
                    R.drawable._georgia,
                    R.drawable._germany,
                    R.drawable._greece,
                    R.drawable._hungary,
                    R.drawable._iceland,
                    R.drawable._ireland,
                    R.drawable._italy,
                    R.drawable._latvia,
                    R.drawable._liechtenstein,
                    R.drawable._lithuania,
                    R.drawable._luxembourg,
                    R.drawable._malta,
                    R.drawable._moldova,
                    R.drawable._monaco,
                    R.drawable._montenegro,
                    R.drawable._netherlands,
                    R.drawable._norway,
                    R.drawable._poland,
                    R.drawable._portugal,
                    R.drawable._macedonia,
                    R.drawable._romania,
                    R.drawable._russia,
                    R.drawable._san_marino,
                    R.drawable._serbia,
                    R.drawable._slovakia,
                    R.drawable._slovenia,
                    R.drawable._spain,
                    R.drawable._sweden,
                    R.drawable._swaziland,
                    R.drawable._turkey,
                    R.drawable._ukraine,
                    R.drawable._united_kingdom,
                    R.drawable._vatican_city
            };

    public static String EuropeanNames[] = {
            "Republic of Albania",
            "Principality of Andorra",
            "Republic of Armenia",
            "Republic of Austria",
            "Republic of Azerbaijan",
            "Republic of Belarus",
            "Kingdom of Belgium",
            "Bosnia and Herzegovina",
            "Republic of Bulgaria",
            "Republic of Croatia",
            "Republic of Cyprus",
            "Czech Republic",
            "Kingdom of Denmark",
            "Republic of Estonia",
            "Republic of Finland",
            "French Republic",
            "Georgia",
            "Federal Republic of Germany",
            "Hellenic Republic",
            "Hungary",
            "Republic of Iceland",
            "Ireland",
            "Italian Republic",
            "Republic of Latvia",
            "Principality of Liechtenstein",
            "Republic of Lithuania",
            "Grand Duchy of Luxembourg",
            "Republic of Malta",
            "Republic of Moldova",
            "Principality of Monaco",
            "Montenegro",
            "Kingdom of the Netherlands",
            "Kingdom of Norway",
            "Republic of Poland",
            "Portuguese Republic",
            "Republic of Macedonia",
            "Romania",
            "Russian Federation",
            "Republic of San Marino",
            "Republic of Serbia",
            "Slovak Republic",
            "Republic of Slovenia",
            "Kingdom of Spain",
            "Kingdom of Sweden",
            "Swiss Confederation",
            "Republic of Turkey",
            "Ukraine",
            "United Kingdom of Great Britain and Northern Ireland",
            "Vatican City State"

    };
    public static String EurupeArea[] = {
            "28,748 ",
            "468",
            "29,743 ",
            "83,871 ",
            "86,600",
            "207,600 ",
            "30,528 ",
            "51,197 ",
            "110,879",
            "56,594 ",
            "9,251 ",
            "78,867 ",
            "43,094 ",
            "45,228 ",
            "338,145 ",
            "643,427",
            "69,700 ",
            "357,022",
            "131,957",
            "93,028 ",
            "103,000 ",
            "70,273 ",
            "301,340",

            "64,589 ",
            "160 km2",
            "65,300 ",
            "2,586 ",
            "316 ",
            "33,851 ",
            "2 ",
            "13,812 ",
            "41,543 ",
            "323,802  ",
            "312,685 ",
            "92,090 ",
            "25,713 ",
            "238,391 ",
            "17,098,242 ",
            "61 ",
            "88,361 ",
            "49,035 ",
            "20,273 ",
            "505,370 ",
            "450,295 ",
            "41,277 ",
            "783,562 ",
            "603,550",
            "243,610 ",
            "0.44 "
    };


    public static String CapitalCities[] = {
            "Tirana",
            "la Vella",
            "Yerevan",
            "Vienna",
            "Baku",
            "Minsk",
            "Brussels",
            "Sarajevo",
            "Sofia",
            "Zagreb",
            "Nicosia",
            "Prague",
            "Copenhagen",
            "Tallinn",
            "Helsinki",
            "Paris",
            "Tbilisi",
            "Berlin",
            "Athens",
            "Budapest",
            "Reykjavik",
            "Dublin",
            "Rome",

            "Riga",
            "Vaduz",
            "Vilnius",
            "Luxembourg",
            "Valletta",
            "Chisinau",
            "Monaco",
            "Podgorica",
            "Amsterdam",
            "Oslo",
            "Warsaw",
            "Lisbon",
            "Skopje",
            "Bucharest",
            "Moscow",
            "San Marino",
            "Belgrade",
            "Bratislava",
            "Ljubljana",
            "Madrid",
            "Stockholm",
            "Bern",
            "Ankara",
            "Kyiv",
            "London",
            "Vatican City"
    };
    public static int PhoneCodes[] = {
            355,
            376,
            374,
            43,
            994,
            375,
            32,
            387,
            359,
            385,
            90392,
            420,
            45,
            372,
            358,
            33,
            995,
            49,
            30,
            36,
            354,
            353,
            39,

            371,
            423,
            370,
            352,
            356,
            373,
            377,
            382,
            31,
            47,
            48,
            351,
            389,
            40,
            7,
            378,
            381,
            421,
            386,
            34,
            46,
            41,
            90,
            380,
            44,
            379,
    };

    public static String EuCurrencies[] = {
            " L ALL",
            "€ EUR",
            "dram  AMD",
            " € EUR",
            "manat  AZN",
            "BYR BYR",
            " € EUR",
            "KM BAM",
            " лв BGN",
            "kn HRK",
            " € EUR",
            " Kč CZK",
            "kr. DKK",
            " € EUR",
            "€ EUR",
            "€ EUR",
            "GEL",
            "€ EUR",
            "€ EUR",
            " Ft HUF",
            " kr Íkr",
            " € EUR",
            " € EUR",
            " € EUR",
            "CHF CHF",
            " € EUR",
            " € EUR",
            " € EUR",
            " € EUR",
            "L MDL",
            " € EUR",
            " € EUR",
            " € EUR",
            " kr",
            "zł PLN",
            " € EUR",
            "lei RON",
            "руб р.",
            " € EUR",
            " РСД  RSD",
            "€ EUR",
            "€ EUR",
            "€ EUR",
            "kr SEK",
            "CHF CHF",
            "TL TRY",
            " ₴  UAH",
            "£  GBP",
            "€ EUR",
            "€ EUR"
    };
}
