package com.apps.mounir.funwithflags.Resources;

import com.apps.mounir.funwithflags.R;

/**
 * Created by mounir on 07.02.2016.
 */
public class NAmerica {

    public static int[] NAmerica =
            {
                    R.drawable._antigua_and_barbuda,
                    R.drawable._bahamas,
                    R.drawable._barbados,
                    R.drawable._belize,
                    R.drawable._canada,
                    R.drawable._costa_rica,
                    R.drawable._cuba,
                    R.drawable._dominica,
                    R.drawable._dominican_republic,
                    R.drawable._el_salvador,
                    R.drawable._grenada,
                    R.drawable._guatemala,
                    R.drawable._haiti,
                    R.drawable._honduras,
                    R.drawable._jamaica,
                    R.drawable._mexico,
                    R.drawable._nicaragua,
                    R.drawable._panama,
                    R.drawable._saint_kitts_and_nevis,
                    R.drawable._saint_lucia,
                    R.drawable._saint_vincent_and_the_grenadines,
                    R.drawable._trinidad_and_tobago,
                    R.drawable._united_states_of_america
            };

    public static String Namescountries[] = {
            "Antigua and Barbuda",
            "Commonwealth of The Bahamas",
            "Barbados",
            "Belize",
            "Canada",
            "Republic of Costa Rica",
            "Republic of Cuba",
            "Commonwealth of Dominica",
            "Dominican Republic",
            "Republic of El Salvador",
            "Grenada",
            "Republic of Guatemala",
            "Republic of Haiti",
            "Republic of Honduras",
            "Jamaica",
            "United Mexican States",
            "Republic of Nicaragua",
            "Republic of Panama",
            "Federation of Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "Republic of Trinidad and Tobago",
            "United States of America"
    };
    public static String CapitalCities[] = {
            "St. John's",
            "Nassau",
            "Bridgetown",
            "Belmopan",
            "Otawa",
            "San José",
            "Havana",
            "Roseau",
            "Santo Domingo",
            "San Salvador",
            "St. George's ",
            "Guatemala City",
            "Port-au-Prince",
            "Tegucigalpa",
            "Kingston",
            "Mexico City",
            "Managua",
            "Panama City",
            "Basseterre",
            "Castries",
            "Kingstown",
            "Port of Spain",
            "Washington, D.C."
    };

    public static String Currencies[] = {
            "East Caribbean dollar",
            "Bahamian dollar",
            "Barbadian dollar",
            "Belize dollar",
            "Canadian dollar",
            "Costa Rican colón",
            "Cuban peso",
            "East Caribbean dollar",
            "Dominican Peso",
            "United States dollar",
            "East Caribbean dollar",
            "Guatemalan quetzal",
            "Haitian gourde",
            "Honduran lempira",
            "Jamaican dollar",
            " Mexican Peso",
            " Nicaraguan córdoba",
            "Panamanian balboa,\n United States dollar",
            "East Caribbean dollar",
            "East Caribbean dollar",
            "East Caribbean dollar",
            "Trinidad and Tobago dollar",
            "United States dollar"
    };


    public static int Areas[] = {
            442,
            13943,
            430,
            22966,
            9984670,
            51100,
            109886,
            751,
            48671,
            21041,
            344,
            108889,
            27750,
            112492,
            10991,
            1128,
            1964375,
            75417,
            261,
            539,
            389,
            5130,
            9629091,
    };
    public static String phonecodes[] = {
            "1 242",
            "1 246",
            "501",
            "506",
            "1",
            "53",
            "1 767",
            "1 809 ",
            " 1 829  \n 1 849",
            "503",
            "1 473",
            "502",
            "509",
            "504",
            "1 876",
            "52",
            "505",
            "507",
            "1 869",
            "1 758",
            "1 784",
            "1 868",
            "1"
    };
}
