package com.apps.mounir.funwithflags;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;

/**
 * Created by mounir on 06.02.2016.
 */
public class AFRICA {

    public static int[] Africa = {
            R.drawable._algeria,
            R.drawable._angola,
            R.drawable._benin,
            R.drawable._botswana,
            R.drawable._burkina_faso,
            R.drawable._burundi,
            R.drawable._cape_verde,
            R.drawable._cameroon,
            R.drawable._central_african_republic,
            R.drawable._chad,
            R.drawable._comoros,
            R.drawable._democratic_republic_of_the_congo,
            R.drawable._djibouti,
            R.drawable._egypt,
            R.drawable._equatorial_guinea,
            R.drawable._eritrea,
            R.drawable._ethiopia,
            R.drawable._gabon,
            R.drawable._gambia,
            R.drawable._ghana,
            R.drawable._guinea,
            R.drawable._guinea_bissau,
            R.drawable._ivory_coast,
            R.drawable._kenya,
            R.drawable._lesotho,
            R.drawable._liberia,
            R.drawable._libya,
            R.drawable._madagascar,
            R.drawable._malawi,
            R.drawable._mali,
            R.drawable._mauritania,
            R.drawable._mauritius,
            R.drawable._morocco,
            R.drawable._mozambique,
            R.drawable._namibia,
            R.drawable._niger,
            R.drawable._nigeria,
            R.drawable._republic_of_the_congo,
            R.drawable._rwanda,
            R.drawable._sao_tome_and_principe,
            R.drawable._senegal,
            R.drawable._seychelles,
            R.drawable._sierra_leone,
            R.drawable._somalia,
            R.drawable._south_africa,
            R.drawable._south_sudan,
            R.drawable._sudan,
            R.drawable._swaziland,
            R.drawable._tanzania,
            R.drawable._togo,
            R.drawable._tunisia,
            R.drawable._uganda,
            R.drawable._western_sahara,
            R.drawable._zambia,
            R.drawable._zimbabwe
    };


    public static String AfricanLongName[] = {
            "People's Democratic Republic of Algeria",
            "Republic of Angola",
            "Republic of Benin",
            "Republic of Botswana",
            "Burkina Faso",
            "Republic of Burundi",
            "Republic of Cabo Verde",
            "Republic of Cameroon",
            "Central African Republic",
            "Republic of Chad",
            "Union of the Comoros",
            "Democratic Republic of the Congo",
            "Republic of Djibouti",
            "Arab Republic of Egypt",
            "Republic of Equatorial Guinea",
            "State of Eritrea",
            "Federal Democratic Republic of Ethiopia",
            "Gabonese Republic",
            "Republic of the Gambia",
            "Republic of Ghana",
            "Republic of Guinea",
            "Republic of Guinea-Bissau",
            "Republic of Côte d'Ivoire",
            "Republic of Kenya",
            "Kingdom of Lesotho",
            "Republic of Liberia",
            "State of Libya",
            "Republic of Madagascar",
            "Republic of Malawi",
            "Republic of Mali",
            "Islamic Republic of Mauritania",
            "Republic of Mauritius",
            "Kingdom of Morocco",
            "Republic of Mozambique",
            "Republic of Namibia",
            "Republic of Niger",
            "Federal Republic of Nigeria",
            "Republic of the congo",
            "Republic of Rwanda",
            "Democratic Republic of São Tomé and Príncipe",
            "Republic of Senegal",
            "Republic of Seychelles",
            "Republic of Sierra Leone",
            "Federal Republic of Somalia",
            "Republic of South Africa",
            "Republic of South Sudan",
            "Republic of Sudan",
            "Kingdom of Swaziland",
            "United Republic of Tanzania",
            "Togolese Republic",
            "Tunisian Republic",
            "Republic of Uganda",
            "Sahrawi Arab Democratic Republic",
            "Republic of Zambia",
            "Republic of Zimbabwe"
    };
    public static String AfricanCapitalCities[] = {
            "Algiers \n: الجزائر \n (al-Jazā’er)",
            "Luanda  ",
            "Porto-Novo  ",
            "Gaborone  \n Tswana: Gaborone",
            "Ouagadougou ",
            "Bujumbura   ",
            "Praia \n Portuguese: Praia",
            "Yaoundé  ",
            "Bangui",
            "N'Djamena \n نجامينا () ",
            "Moroni \n : موروني ()  ",
            "Kinshasa  \n Léopoldville",
            "Djibouti  City  \n مدينة جيبوتي ( ) \n Ville de Djibouti",
            "Cairo \n القاهرة (al-)",
            "Malabo ",
            "Asmara  \n أسمرة ()  \nTigrinya:\n ኣስመራ(Asmera)",
            "Addis Ababa  \nAmharic:\n አዲስ አበባ ",
            "Libreville  \nFrench:\n Libreville",
            "Banjul ",
            "Accra ",
            "Conakry ",
            "Bissau ",
            "Yamoussoukro ",
            "Nairobi ",
            "Maseru ",
            "Monrovia ",
            "Tripoli \n: طرابلس  \nAmazigh: \nⵟⵔⴰⴱⵍⴻⵙ",
            "Antananarivo ",
            "Lilongwe",
            "Bamako ",
            "Nouakchott \n نواكشوط ()",
            "Port Louis",
            "Rabat \n: الرباط \n: ⴰⵕⴱⴰⵟ (Aṛbaṭ)",
            "Maputo ",
            "Windhoek ",
            "Niamey ",
            "Abuja ",
            "Brazzaville ",
            "Kigali  ",
            "São Tomé \nPortuguese: São Tomé",
            "Dakar \nFrench: Dakar",
            "Victoria \nEnglish: Victoria \nFrench: Victoria \nSeychellois \nCreole: Victoria",
            "Freetown \nEnglish: Freetown",
            "Mogadishu \nArabic: مقديشو",
            "Bloemfontein \n(judicial)\nCape Town \n(legislative)",
            "Juba ",
            "Khartoum \nArabic: الخرطوم \n(al-Kharṭūm)",
            "Lobamba \n(royal and legislative)\n Mbabane \n(administrative)\nEnglish: Lobamba, \nMbabane \nSwazi: Lobamba, \nÉMbábáne",
            "Dodoma ",
            "Lomé ",
            "Tunis \n تونس ",
            "Kampala ",
            "El Aiun ",
            "Lusaka ",
            "Harare "
    };

    public static String AfricanArea[] = {
            "2,381,740",
            " 1,246,700",
            " 112,622 ",
            "581,726 ",
            "274,000 ",
            "27,830 ",
            "475,442 ",
            "4,033 ",
            "622,984 ",
            "1,284,000",
            "2,235 ",
            "2,344,858 ",
            "23,200 ",
            "1,001,449 ",
            "28,051 ",
            "117,600 ",
            "1,104,300 ",
            "267,668",
            "10,380 ",
            "238,534 ",
            "245,857 ",
            "36,125 ",
            "322,460 ",
            "580,367 ",
            "30,355 ",
            " 111,369 ",
            "1,759,540 ",
            "587,041 ",
            " 118,484 ",
            "1,240,192",
            "1,030,700",
            "2,040 ",
            "446,550 ",
            "801,590 ",
            "825,418 ",
            "1,267,000 ",
            " 342,000 ",
            "923,768 ",
            "26,798 ",
            "964 ",
            " 196,723 ",
            "451 ",
            "71,740 ",
            " 637,657 ",
            "1,221,037 ",
            "644,329 ",
            " 1,861,484 ",
            "17,364 ",
            " 945,203 ",
            "56,785 ",
            "163,610 ",
            "236,040 ",
            "267,405 ",
            " 752,614 ",
            "390,757 "

    };
    public static int AfricanPopulation[] = {
            39903000,
            25326000,
            1078200,
            2176000,
            18450000,
            9824000,
            21918000,
            525000,
            4900000,
            13675000,
            783000,
            77267000,
            961000,
            88523000,
            1996000,
            6895000,
            90076000,
            1873000,
            2022000,
            27714000,
            10935000,
            1788000,
            23326000,
            44234000,
            1908000,
            4046000,
            6278000,
            23043000,
            16307000,
            17796000,
            3632000,
            1263000,
            33680000,
            25728000,
            2281000,
            18880000,
            184000000,
            4706000,
            11324000,
            14150000,
            97000,
            6513000,
            10972000,
            54957000,
            12519000,
            38435000,
            1119000,
            194000,
            48829000,
            7065000,
            11118000,
            35760000,
            509000,
            15474000,
            13503000,

    };

    public static String Region(int inex) {
        switch (inex) {
            case 1:
                return "Northeast Africa";
            case 2:
                return "Central Africa";
            case 3:
                return "Westren Africa";
            case 4:
                return "Southern Africa";
            case 5:
                return "Eastern Africa";
            case 6:
                return "Horn Of Africa";

        }
        return "Region Not Found";
    }

    public static String AfricanCurrencies[] = {
            "Algerian dinar",
            "Kwanza",
            "CFA franc",
            "Pula",
            "CFA franc",
            "Burundi franc",
            "Cape Verdean escudo",
            "CFA franc",
            "CFA franc",
            "CFA franc",
            "Comorian franc",

            "Congolese franc",
            "Djiboutian franc",
            "Egyptian pound",
            "CFA franc",
            "Nakfa",
            "Ethiopian birr",
            "CFA franc",
            "Dalasi",
            "Ghanaian cedi",
            "Guinean franc",
            "CFA franc",
            "CFA franc",
            "Kenyan shilling",
            "Loti",
            "Liberian dollar",
            "Libyan dinar",
            "Malagasy ariary",
            "Malawian kwacha",
            "CFA franc",
            "Ouguiya",
            "Mauritian rupee",
            "Moroccan dirham",
            "Mozambican metical",
            "Namibian dollar",
            "CFA franc",
            "Naira",
            "CFA franc",
            "Rwandan franc",
            "Dobra",
            "CFA franc",
            "Seychellois rupee",
            "Sierra Leonean leone",
            "shilling",
            "South African rand",
            "South Sudanese pound",
            "Sudanese pound",
            "Lilangeni",
            "Tanzanian shilling",
            " CFA franc",
            "Tunisian dinar",
            "Ugandan shilling",
            "Algerian Dinar \n Sahrawi Pesata",
            "Zambian kwacha",
            "Zimbabwean dollar\n(No longer in use)"
    };
    public static String RegionNorthern_Africa[] = {" Algeria ",
            " Canary Islands (Spain)[131] \n",
            "Santa Cruz de Tenerife\n",
            " Ceuta (Spain)[132] \n",
            " Egypt[133] \n",
            " Libya \n",
            " Madeira (Portugal)[134] \n",
            " Melilla (Spain)[135] \n",
            " Morocco \n",
            " Sudan \n",
            " Tunisia \n",
            " Western Sahara[136] \n"
    };
    public static String RegionNortheast_Africa[] = {" Djibouti ",
            " Eritrea ",
            " Ethiopia ",
            " Somalia ",
            "Eastern Afric"
    };
    public static String RegionEastern_Africa[] = {" " +
            "Burundi \n",
            " British Indian Ocean Territory - Chagos Archipelago\n",
            "(United Kingdom) \n",
            " Comoros \n",
            " Kenya \n",
            " Madagascar \n",
            " Malawi \n",
            " Mauritius \n",
            " Mayotte (France) \n",
            " Mozambique \n",
            " Réunion (France) \n",
            " Rwanda \n",
            " Seychelles \n",
            " South Sudan \n",
            " Tanzania \n",
            " Uganda \n",
            " Zambia \n",
            " Zimbabwe \n"};

    public static String RegionCentral_Africa[] = {
            " Angola \n",
            " Cameroon \n",
            " Central African Republic \n",
            " Chad \n",
            " Republic of the Congo \n",
            " Democratic Republic of the Congo \n",
            " Equatorial Guinea \n",
            " Gabon \n",
            " São Tomé and Príncipe \n"};

    public static String RegionSouthern_Africa[] = {" Botswana \n" +
            " Lesotho \n" +
            " Namibia \n" +
            " South Africa \n" +
            " Swaziland\n"};

    public static String RegionWestren_Africa[] = {" Benin \n",
            " Burkina Faso ",
            " Cape Verde ",
            " Gambia ",
            " Ghana ",
            " Guinea ",
            " Guinea-Bissau ",
            " Ivory Coast",
            " Liberia",
            " Mali ",
            " Mauritania ",
            " Niger ",
            " Nigeria ",
            " Saint Helena, Ascension and Tristan da Cunha (United Kingdom) \n",
            " Senegal ",
            " Sierra Leone ",
            " Togo"};
    public static String AfricanISO[] = {
            "   DZD",
            "        AOA",
            "        XOF",
            "        BWP",
            "        XOF",
            "        BIF",
            "        XAF",
            "        CVE",
            "        XAF",
            "        XAF",
            "        KMF",
            "        XAF",
            "        CDF",
            "        DJF",
            "        EGP",
            "        XAF",
            "        ERN",
            "        ETB",
            "        XAF",
            "        GMD",
            "        GHS",
            "        GNF",
            "        XOF",
            "        XOF",
            "        KES",
            "        LSL",
            "        LRD",
            "        LYD",
            "        MGA",
            "        MWK",
            "        XOF",
            "        MRO",
            "        MUR",
            "        MAD",
            "        MZN",
            "        NAD",
            "        XOF",
            "        NGN",
            "        RWF",
            "        STD",
            "        XOF",
            "        SCR",
            "        SLL",
            "        SOS",
            "        ZAR",
            "        SSP",
            "        SDG",
            "        SZL",
            "        TZS",
            "        XOF",

            "        TND",
            "        UGX",
            "DZD",
            "        ZMW",
            "        ZWD "
    };
    public static int Phonecode[] = {
            213,
            244,
            229,
            267,
            226,
            257,
            238,
            237,
            236,
            235,
            269,
            243,
            253,
            20,
            240,
            291,
            251,
            241,
            220,
            233,
            240,
            245,
            225,
            254,
            266,
            231,
            218,
            261,
            265,
            223,
            222,
            230,
            212,
            258,
            264,
            227,
            234,
            242,
            250,
            239,
            221,
            248,
            232,
            252,
            27,
            211,
            249,
            268,
            255,
            228,
            216,
            256,
            212,
            260,
            263
    };
    public static int Region[] = {
            1,
            2,
            3,
            4,
            3,
            5,
            3,
            2,
            2,
            2,
            5,
            2,
            6,
            1,
            2,
            6,
            6,
            2,
            3,
            3,
            2,
            3,
            3,
            5,
            4,
            3,
            1,
            5,
            5,
            3,
            3,
            5,
            1,
            5,
            4,
            3,
            3,
            2,
            5,
            2,
            3,
            5,
            3,
            6,
            4,
            1,
            1,
            4,
            5,
            3,
            1,
            5,
            3,
            4,
            4
    };


}
